.\"	@(#)sumcheck.8	
.\"
.TH DUMPSUM 8 "May 1, 2001"
.AT 3
.SH NAME
dumpsum \- print contents of a Backtalk summary file
.SH SYNOPSIS
.B dumpsum
sumfile
.SH DESCRIPTION
.I Dumpsum
Prints the contents of a Backtalk, Picospan or Yapp conference summary file
in a human readable format.  This is a debugging tool only.
.SH AUTHORS
Jan Wolter
(backtalk@hvcn.org)
.SH "SEE ALSO"
.IR sumcheck (8)
