#include <stdio.h>

#include "tags.h"

int main(int argc, char **argv)
{
    int i;

    printf("/* DO NOT EDIT THIS FILE\n"
	   " * It is automatically generated from tags.c by mktagdefs.c.\n"
	   " */\n\n");
    for (i= 0; tagtype[i].name != NULL; i++)
    {
	if (i != 0 && strcmp(tagtype[i-1].name,tagtype[i].name) > 0)
	{
	    fprintf(stderr,"Tags %s and %s in tags.c not in order\n",
		    tagtype[i-1].name,tagtype[i].name);
	    exit(1);
	}
	printf("#define Tag_%s %d\n", tagtype[i].name, i);
    }
    printf("\n#define N_TAGS %d\n",i);
    exit(0);
}
