#!/bin/sh
#
# This is a script to install backtalk.  It should be usable for
# upgrades as well as for initial installs.
#
# Note that new backtalk installs do not overwrite the old ones, for the
# most part.  Backtalk directories have the version number in them.

BACKTALK=backtalk-1.3.30
FRONTALK=fronttalk-0.9.2

../${BACKTALK}/misc/btinstall

# install fronttalk client program
#cd /cyberspace/src/${PROG}/${FRONTTALK}
mkdir -p /cyberspace/lib/${FRONTTALK}
chmod 755 /cyberspace/lib/${FRONTTALK}
#cp -f lib/* /cyberspace/lib/${FRONTTALK}
#mkdir -p /cyberspace/lib/${FRONTTALK}/help
#chmod 755 /cyberspace/lib/${FRONTTALK}/help
#cp -f help/* /cyberspace/lib/${FRONTTALK}/help
#sed "s/fronttalk-X.Y.Z/${FRONTTALK}/g" < ${GREXDOCDIR}/fronttalk.config.pl > /cyberspace/lib/${FRONTTALK}/config.pl
#chmod 644 /cyberspace/lib/${FRONTTALK}/config.pl
#cp ${GREXDOCDIR}/fronttalk.syslist /cyberspace/lib/${FRONTTALK}/syslist
#chmod 644 /cyberspace/lib/${FRONTTALK}/syslist
#sed "s%/home/jan/src/backtalk/fronttalk/lib%/cyberspace/lib/${FRONTTALK}%" < ft > /cyberspace/bin/${FT}
#chmod 755 /cyberspace/bin/${FT}

#ln -sf ${FT} /cyberspace/bin/ft
#ln -sf ${FT} /cyberspace/bin/bbs
