letter: letter.c sys.c sys.h
	cc -o letter letter.c sys.c

letter.tar: letter.c sys.c sys.h pure/word-01 pure/word-02 pure/word-03 \
	pure/word-04 pure/word-05 pure/word-06 pure/word-07 pure/word-08 \
	pure/word-09 pure/word-10 pure/word-11 pure/word-12 pure/word-13 \
	pure/word-14 pure/word-15 pure/word-16 pure/word-17 pure/word-18 \
	pure/word-19 pure/word-20 Makefile letter.1
	tar cvf letter.tar \
	letter.c sys.c sys.h pure/word-01 pure/word-02 pure/word-03 \
	pure/word-04 pure/word-05 pure/word-06 pure/word-07 pure/word-08 \
	pure/word-09 pure/word-10 pure/word-11 pure/word-12 pure/word-13 \
	pure/word-14 pure/word-15 pure/word-16 pure/word-17 pure/word-18 \
	pure/word-19 pure/word-20 Makefile letter.1
