#!/bin/sh
#Author- Michelangelo Giansiracusa

echo "
UNIX: mv <existing-filename> <new-filename>"
sleep 1
echo "
Listing Directory (`pwd`):
"
sleep 1
ls -p | grep -v /\$ | menumore
echo -n "
File name to rename? "
read ex_filename
echo -n "
New filename? "
read new_filename
/bin/mv $ex_filename $new_filename
