#!/bin/sh
# listal -- a generic command to list the ultimate target of an alias
# written 11 Jan 93 by mju@grex.
# non-mnemonic name ("listalias" is preferable) because Elm has already
# taken "listalias".

if [ $# -lt 1 ]; then
	echo "$0: usage: $0 alias [alias ...]"
	exit 1
fi

for alias in "$@"; do
	target="$alias"
	while :; do
		oldtarget="$target"
		target=`grep '^'"$oldtarget"':' /etc/mail/aliases |
			awk -F: '{print $2}' | sed 's/ //g'`
		if [ -z "$target" ]; then
			target="$oldtarget"
			break
		fi
	done
	( echo -n "${alias}: "
	  echo $target | sed 's/,/, /g'
	) | fmt -79
done
